name = "gif-land"
compatibility_date = "2025-03-19"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

# R2 Storage binding for assets
[[r2_buckets]]
binding = "gifLandR2"
bucket_name = "gifland"
preview_bucket_name = "gifland" # Use the same bucket for preview
